-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglU5HmdFchL2meXe+
lhE5h8zssUVZa7c0yxpOQv4v43CgCgYIKoZIzj0DAQehRANCAASzmgUjhAi+D/89
yyhAwdegoqCsjXNw1Fj0KTjJheNswtOVjpOqCl9QdbHnqwvWdcIEUC+xOV89EWAN
+3xC6kWl
-----END PRIVATE KEY-----